### ISSUE TITLE
Allow user to ignore files

### ISSUE THREAD

**Issue by Guergeiro** [habamax/vim-select#4]
When using the `:Select projectfile`, all files are shown that fuzzymatch. This is a good behaviour by default, but I feel like an optional flag to stop this would be interesting. I don't know the best, maybe a `let g:respect_ignore_vcs` would be a solution.
In my use case, I have a `node_modules` folder that I don't want to search through... Or maybe make it respect the `&path`?

**Comment by habamax** [comment]
It would be very ineffective to filter files in vim, so I didn't even try to implement it.

So I just rely on uses `rg` or `fd` which `Select projectfile` uses. Both tools use `.ignore` file to filter stuff.

There might be global `~/.ignore` or local in project directory `~/somdir/project1/.ignore`:

For example, for my `~/.vim/.ignore` I have ignored:

```
pack/minpac/
```

Also as a default, `Select projectfile` ignores (passed as a parameter to `rg`) `.git` dir:
https://github.com/habamax/vim-select/blob/175503c44b2913c894e0b7fc9fff82fc2f7ee1dd/autoload/select/def.vim#L40

On the other hand, there is vim-select-more extension plugin, that has `Select gitfile` and it will only let you select what is in the repo.

**Comment by habamax** [comment]
It might be a good idea to have a setting, smth like `let g:select_ignore_vcs = 1` that would either use `.gitignore` or not.
Basically, whether `rg` would have `--no-ignore-vcs` or not.

PS And looks like this actually what you have suggested :)

**Comment by habamax** [comment]
@Guergeiro could you add to your vimrc:

```
let g:select_info = {'projectfile': {}}
let g:select_info.projectfile.data = {'job': 'rg --files'}
```
and try `Select projectfile`?

**Comment by Guergeiro** [comment]
> It might be a good idea to have a setting, smth like `let g:select_ignore_vcs = 1` that would either use `.gitignore` or not.
> Basically, whether `rg` would have `--no-ignore-vcs` or not.
> 
> PS And looks like this actually what you have suggested :)

This is exactly what I meant. Because I feel like the API would be easier for end users (even myself).

**Comment by Guergeiro** [comment]
> @Guergeiro could you add to your vimrc:
> 
> ```
> let g:select_info = {'projectfile': {}}
> let g:select_info.projectfile.data = {'job': 'rg --files'}
> ```
> 
> and try `Select projectfile`?

This works. But we are assuming I'm using ripgrep... What about `fd`? I feel like a variable that adds `--no-ignore-vcs` to the job command would be better since the user wouldn't have to override the command.

**Comment by habamax** [comment]
> But we are assuming I'm using ripgrep... What about fd?

I am not sure this is an issue as one can put whatever command there: `fg -type f` or smth.

I don't think I would implement this option myself as I think there is an obvious (If well documented) way to achieve desired effect.

But, you have already provided PR... let's continue there.
