### ISSUE TITLE
Not compatible with WSL2

### ISSUE THREAD

**Issue by Guergeiro** [habamax/vim-select#7]
### Problem
When using any of the api commands created by vim-select (`:Select projectfile`, `:Select file`, etc) and after typing the first character, an error occurs.
This only occurs when typing; using *TAB*/*S-TAB* to navigate through the files works normally.
Using the provided key bindings to interact with files also works, like *\<c-v\>*, *\<c-s\>*, *\<cr\>*.

![Capture](https://user-images.githubusercontent.com/39097691/103565438-4005c100-4eb8-11eb-9a0d-f28eb1377081.PNG)

### System specs
- **OS:** Windows10
- **WSL2 OS:** Ubuntu 20.04

### `.vimrc` used for test
```vim
" Install VimPlug automatically
if empty(glob("~/.vim/autoload/plug.vim"))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif
" Let's load plugins
call plug#begin("~/.vim/plugged")
Plug 'habamax/vim-select'
call plug#end()
```

**Comment by habamax** [comment]
`matchfuzzypos` func was changed recently to return additional `score` list.

Let me fix it...

**Comment by habamax** [comment]
Could you try it?

**Comment by Guergeiro** [comment]
> Could you try it?

Working! Both on Ubuntu and Windows!

**Comment by habamax** [comment]
Nice, thx!
