### ISSUE TITLE
Request: send selection/s to quickfix/location list

### ISSUE THREAD

**Issue by craigmac** [habamax/vim-select#9]
This would be the feature for me that could get to me leave FZF, everything else you have covered. Is it possible to do something like this in this way you've wrote this plugin? In FZF in any list I can hit `<Tab>` to place markers next to items in the results list, and then I have `^[q` bound to send all selected items to the quickfix list, so then I can do a `:cdo ...` on them all.

**Comment by habamax** [comment]
is it only about files/buffers?

**Comment by craigmac** [comment]
My use case is only for files, I select a bunch of files from different locations in the project that I need to change a typo in for example, then I load them into the quickfix list.

**Comment by habamax** [comment]
got it, will think about implementation
